<?php

namespace Stage\RestorePhoneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReparationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparationRepository extends EntityRepository
{
    public function findByOne($data)

    {

        $query = $this->createQueryBuilder('r');
        $query  ->where('r.Nom LIKE :nomClient')

                ->andWhere('r.IMEI LIKE :IMEITelephone')

                
                
                ->setParameters(array(
                    'nomClient' => $data['Nom'],

                    'IMEITelephone' => $data['IMEI']));
        return $query->getQuery()->getResult();

    }
}
