stage_restore_phone:
    resource: "@StageRestorePhoneBundle/Controller/"
    type:     annotation
    prefix:   /

tdtravel_advisor:
    resource: "@tdtravelAdvisorBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

voyage:
    path: /voyage

redirection:
    path: /voyage/visiteur
